# Generated by Django 5.1.4 on 2024-12-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoowl_app', '0005_remove_book_status_borrowhistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
